name: "Update PR body"
description: "Update PR body because PR comments are annoying :)"
inputs:
  body:
    description: "body"
    required: true
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run shell script
      shell: bash
      run: ${{ github.action_path }}/DeployDockerImage.sh ${{ inputs.body }}  ${{ inputs.GITHUB_TOKEN }} 
