name: "Update PR description"
description: "Updates PR description with github actions results"
inputs:
  body:
    description: "description"
    required: true
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "link"
  color: "blue"
